lidofinance/ui

.storybook/main.js, packages/input/package.json, packages/input/src/Input.stories.tsx, packages/input/src/Input.tsx, packages/input/src/InputStyles.ts, packages/input/src/LabelStyles.ts, packages/input/src/types.ts, packages/theme/src/base/colors.ts, yarn.lock
=> Accent color for input

packages/input/src/Input.stories.tsx, packages/input/src/InputStyles.ts, packages/popup-menu/src/PopupMenuItemStyles.ts, packages/select/src/Select.stories.tsx, packages/theme/src/themes.ts
Update input component (input and select like design system https://www.figma.com/file/0j4EJ3Ra7OPBeEKLXFQiGM/LIDO-Design-System?node-id=11311%3A356 see components tab)
Affected: select components, popups components and color components
=> Update input component

packages/icons/src/index.tsx, packages/icons/src/svg/warning.svg
This PR adds a new icon `Warning`.
Preview
=> feat: add warning icon

packages/table/package.json, packages/table/src/Table.stories.tsx, packages/table/src/Td.tsx, packages/table/src/Th.tsx, packages/table/src/Thead.tsx, packages/table/src/Tr.tsx, packages/table/src/styles.tsx, packages/table/src/types.tsx, yarn.lock
=> feat: add sort type th, highlight tr,interactive state, sticky header, variants th/td,numeric td

packages/theme/cookie-theme-provider.tsx
Test on UI Storybook
https://user-images.githubusercontent.com/9885789/193805467-09fd59a7-5d01-44e6-8aa1-e233bad69802.mov
Test on Staking ETH widget
https://user-images.githubusercontent.com/9885789/193805393-bc235512-768a-45d4-9195-68c50a936af8.mov
Theme Top Level changing
https://user-images.githubusercontent.com/9885789/194072793-4a1d3294-a7c0-4b03-a3c0-c454301ec250.mov
=> feat: check the cross cookie theme was changed on other tab

packages/input/src/OptionsSlider.stories.tsx, packages/input/src/OptionsSlider.tsx, packages/input/src/SliderInput.stories.tsx, packages/input/src/SliderInput.tsx, packages/input/src/SliderInputStyles.ts, packages/input/src/types.ts
https://linear.app/lidofi/issue/UI-224/implement-component-pseudo-input-with-slider-in-ui-kit
=> feat: add slider and options slider

.github/workflows/checks.yml, .github/workflows/deploy.yml, .github/workflows/test.yml
=> chore: Add static linters

packages/input/OptionsSlider.stories.tsx, packages/input/OptionsSlider.tsx, packages/input/SliderInput.tsx, packages/input/SliderInputStyles.ts, packages/input/types.ts
Remove optionSlider's border + add clickable labels + add a possibility to add several labels
=> feat: update optionSlider

packages/section/Section.stories.tsx, packages/section/Section.tsx, packages/section/SectionStyles.tsx, packages/section/types.ts
=> feat: section component

packages/loaders/LoaderStyles.tsx
Fix loader animation in Safari
=> fix: loader in Safari

packages/input/Input.stories.tsx, packages/input/Input.tsx, packages/input/InputGroupStyles.ts, packages/input/InputStyles.ts, packages/input/LabelStyles.ts, packages/input/Textarea.stories.tsx, packages/input/Textarea.tsx
Fixing input message label issue
=> Fix: input popover message z-index

packages/accordion/Accordion.tsx, packages/address/Address.tsx, packages/block/Block.tsx, packages/chip/Chip.tsx, packages/identicon/Identicon.tsx, packages/loaders/InlineLoader.tsx, packages/loaders/Loader.tsx, packages/utils/types.ts
Basically `ComponentPropsWithoutRef` does what we need
=> Replaced new component props with builtin type

packages/service-page/ServicePage.module.css, packages/service-page/ServicePage.stories.tsx, packages/service-page/ServicePage.tsx, packages/service-page/index.ts, packages/service-page/types.ts
=> Moved service page to css modules

packages/input/Textarea.tsx, packages/modal/Modal.tsx, packages/popup-menu/PopupMenuProvider.tsx, packages/stack/StackProvider.tsx, packages/transition/withTransition.tsx
Move props destruction to component declaration except Accordion component
=> fix: move props destruction to component declaration

packages/modal/ModalOverlay.tsx, packages/popover/PopoverRoot.tsx, packages/select/SelectArrow.tsx, packages/transition/index.ts, packages/transition/withTransition.tsx, packages/utils/index.ts, packages/utils/modalRoot.ts
Change export default to export.
=> fix: remove export default

packages/icons/Icon.stories.tsx
Add import from '.' in .stories.tsx for icons + check that other files are made according to this rule
=> fix: import icons in stories file

packages/addressBadge/AddressBadge.stories.tsx, packages/block/Block.stories.tsx, packages/button/Button.stories.tsx, packages/container/Container.stories.tsx, packages/cookie-theme-toggler/cookie-theme-toggler.stories.tsx, packages/heading/Heading.stories.tsx, packages/icons/Icon.stories.tsx, packages/input/Textarea.stories.tsx, packages/popover/Popover.stories.tsx, packages/popup-menu/PopupMenu.stories.tsx, packages/stack/Stack.stories.tsx
For .stories.tsx replaces as with satisfies
=> fix: replace as with satisfies in stories files

packages/link/Link.tsx, packages/stack/Stack.tsx, packages/stack/StackItem.tsx, packages/table/Td.tsx, packages/table/Th.tsx, packages/table/Thead.tsx, packages/table/Tr.tsx
Add className and style as a props where needed
=> fix: add className amd style props where needed

packages/modal/Modal.tsx
https://github.com/lidofinance/ui/assets/103929444/7145eeb1-26b4-4bd6-8721-c2ac21987a38
- closes on overlay click
- closes on Escape keypress
- closes on X button click
=> Fixed modal onClose overlay handling

.github/CODEOWNERS
We don't have such separation between brand & core any more
=> Set team-ui as a sole codeowner

packages/accordion/Accordion.tsx, packages/accordion/types.ts, packages/accordion/useExpanded.ts
Adding `onExpand` and `onCollapse` callbacks to `<Accordion />` component
=> feat: accordion collapse expand callbacks

packages/input/Input.tsx, packages/input/InputStyles.ts
Add wrap for errors and warnings for inputs
=> feat: add error message wrap for inputs

.github/workflows/deploy.yml, .github/workflows/test.yml, package.json
- Updated workflows
- Added engine field to package.json
- Tested on staking widget via linking, looks like it's working
=> node 16 -> node 20

packages/cookies-tooltip/cookies-tooltip.tsx, packages/cookies-tooltip/styles.tsx, packages/theme/themes.ts
add link styles to privacy notice link in cookie banner + update cookie banner text
https://github.com/lidofinance/ui/assets/44968205/fc4f094b-18b1-4ae6-83cf-b8c9f2855ca8
=> feat: update cookie banner styles + text

.github/actions/merge-storybook-builds/action.yml, .github/workflows/deploy.yml, .github/workflows/test.yml
Corresponding PR to https://github.com/lidofinance/ui/pull/503
=> ci: update sb deploy action

.github/dependabot.yml
Added dependabot config for our main versions' branches
=> feat: config for dependabot branches

.github/workflows/ci-preview-demolish.yml, .github/workflows/ci-preview-deploy.yml
Added workflows to deploy and demolish preview stands.
=> Feature/sre 2805 provide a way to deploy UI repo storybook to preview stands

packages/button/Button.tsx, packages/card/slider-card/SliderCard.module.css, packages/links/link/Link.tsx, packages/select/Select.module.css, packages/select/Select.tsx, packages/select/dropdown/Dropdown.module.css, packages/select/dropdown/Dropdown.tsx, packages/select/utils.tsx, packages/tabs/tabs/Tabs.module.css, packages/tag/Tag.module.css
Fixed errors like this
They are _not checkable_ on CI or CLI, only IDE highlights them, but still deserves a fix
=> fix: ge trid of TS7053 error

.github/workflows/test-visual.yml, chromatic.config.json, package.json, yarn.lock
✨ Add Visual Regression Testing with Chromatic
📌 Summary
This PR integrates Chromatic into our workflow to enable automated visual regression testing for Storybook components.
🔍 What’s Included
- 🔗 Connected project to Chromatic
- ⚙️ Added GitHub Actions workflow for CI integration
- 🖼️ Automatic screenshot generation for each Storybook story
- ✅ Visual diff detection to catch unexpected UI changes
=> feat: add Chromatic visual testing workflow and configuration
