- README.md
- packages/hooks/src/useSystemTheme.ts
Removes default value for system theme hook: if we don't know what system theme is, we should pass that so apps can handle it themselves.
Breaking change: affects app logic.
> Fix: Removing default for system theme identification hook

- packages/icons/src/index.tsx
- packages/icons/src/svg/arrow-back.svg
- packages/modal/src/Modal.stories.tsx
- packages/modal/src/Modal.tsx
- packages/modal/src/ModalOverlay.tsx
- packages/modal/src/ModalStyles.tsx
- packages/modal/src/types.tsx
The new design of the Connect Wallet Modal includes such usage examples of the Modal component:
We can see the Back button and the Subtitle area here, which we haven't in the Modal component before.
This PR adds this required elements. Also I decided to adjust some paddings, margins, colors and else.
> Modal: rework, add Back button, add Subtitle

- .yarnrc.yml
Our releases seem to be blocked by npm throttling. For a potential fix, we are updating and/or bringing new dependencies to the project.
> CI: Missing dependencies of npm plugin for releases

- packages/accordion/src/AccordionStyles.tsx
- packages/address/src/AddressStyles.tsx
- packages/block/src/Block.stories.tsx
- packages/block/src/Block.tsx
- packages/block/src/BlockStyles.tsx
- packages/block/src/types.tsx
- packages/checkbox/package.json
- packages/checkbox/src/Checkbox.stories.tsx
- packages/checkbox/src/Checkbox.tsx
- packages/checkbox/src/CheckboxStyles.tsx
- packages/checkbox/src/types.ts
- packages/data-table/src/DataTableStyles.tsx
- packages/input/src/InputStyles.ts
- packages/modal/src/ModalStyles.tsx
- packages/pagination/src/Pagination.tsx
- packages/popover/src/PopoverStyles.ts
- packages/popup-menu/src/PopupMenuItemStyles.ts
- packages/table/src/styles.tsx
- packages/tooltip/src/TooltipStyles.ts
- yarn.lock
- [changed font-weight: 500 to 400 everywhere](https://github.com/lidofinance/ui/commit/5a58e6ada63b80f9d5ed1eee900d5a0f7cfa0589) agreed with the designer, also because of [makets](https://www.figma.com/file/0j4EJ3Ra7OPBeEKLXFQiGM/LIDO-Design-System?node-id=11311%3A356), there everywhere is 400
- added ability adding label for checkbox, for better UX
- added `paddingLess` props for block component, because of frequent need
- also small fix for pagination component
> Fixes founded in solana staking development

- packages/tooltip/src/TooltipStyles.ts
The problem with padding was on our side because of styled-components and their specificity issue
> fix: tooltip padding

- packages/input/src/Input.stories.tsx
- packages/input/src/Input.tsx
- packages/input/src/InputStyles.ts
- packages/input/src/LabelStyles.ts
- packages/input/src/Textarea.tsx
- packages/input/src/types.ts
This PR adds a `warning` prop for `Input` component. It is used for non-critical messages warning the user that the input value can possibly be invalid.
The prop behaves the same as `error` but uses `warning` color. The `error` prop has a priority over `warning` and it will override it.
Design link: https://www.figma.com/file/66L3gxbUxVhqhXQjy4xzOz/Web?node-id=13522%3A65912
Preview
> feat(input): add a warning prop for input and textarea

- packages/icons/src/Icon.stories.tsx
Reason: github workflow with npm publishing failed, semantic-release do not allow to re-publish the package.
> fix(icons): dummy release

- .github/workflows/deploy.yml
- .github/workflows/test.yml
- It shouldn't be possible to trigger publish from any branch
- NPM_TOKEN should only be available in `main` branch
> Using npm token from environment protection

- packages/theme/base/colors.ts
- packages/theme/themes.ts
Add those colors to ui-library:
color-bg-secondary (light): #EFF2F6
color-bg-secondary (dark): #27272E
color-bg-warning: #FFFAE0  — same on both themes, according designs
color-text-dark: #273852 — same on both themes, for example text on new color-bg-warning
> feat: new theme colors

- packages/input/InputStyles.ts
Old style:
Fixed style: 
Made by analogy with warning and error
> fix: fix input style for success variant

- packages/theme/cookie-theme-provider.tsx
Fix bug with nested CookieThemeProvider.
Flash rendering (about 1 second) with default theme (white theme) and after rendering with parent provider (CookieThemeProvider) theme
Rendering with parent provider (CookieThemeProvider) theme
**SomeWeb3Package.tsx**
```
import { CookieThemeProvider } from '@lidofinance/lido-ui'
// others imports...
export const ProviderWeb3: FC = () => (
<CookieThemeProvider>
...
</CookieThemeProvider>
)
```
**App.tsx**
```
import { CookieThemeProvider } from '@lidofinance/lido-ui'
import { ProviderWeb3 } from 'SomeWeb3Package'
// others imports...
const App: FC = () => (
<ProviderWeb3>
<SomeProviders>
<CookieThemeProvider>
...
</CookieThemeProvider>
</SomeProviders>
</ProviderWeb3>
);
```
> fix: nested cookie theme provider

- packages/input/InputStyles.ts
Fixing a problem with a text color in input that appears when selecting data from input saved autofill suggestion.
> Fix: input autofilled text color

- vite.config.js
- yarn.lock
Looks like with `preserveModules: true` resolution works a bit differently, so it's not needed to write complex `external` function.
```
$ tsc -p tsconfig.build.json
$ vite build
$ yarn build:js && yarn build:types
Done in 14.67s.
computing gzip size...
dist/accordion/Accordion.cjs.js                                  1.28 kB │ gzip:  0.48 kB
dist/accordion/Accordion.es.js                                  1.07 kB │ gzip:  0.41 kB
dist/accordion/AccordionStyles.cjs.js                            2.37 kB │ gzip:  0.84 kB
dist/accordion/AccordionStyles.es.js                            1.88 kB │ gzip:  0.69 kB
dist/accordion/useExpanded.cjs.js                                1.05 kB │ gzip:  0.48 kB
dist/accordion/useExpanded.es.js                                0.75 kB │ gzip:  0.34 kB …
```
> Simplified vite config

- postcss.config.js
We can use browser layers during development:
Because postcss plugin doesn't work on separate files:
But we can still apply it during production build once there are all files. e.g. final selector for `modalButton` is more specific than `button` selector:
```
._modalButton_1qzmn_4:not(#_\#_1qzmn_1):not(#\#):not(#\#) {...}
._button_8csc7_4:not(#\#) {...}
```
> Apply postcss layers plugin during build

- .swcrc
- .swcrc.commonjs
- .swcrc.esm
- scripts/swcrc-template.cjs
Bug showed after https://github.com/lidofinance/ui/pull/449. If we remove manual React imports, then this component won't work anywhere else, because of missing React import.
This issue actually may have fired at any moment because React imports wasn't enforced in any mean, so it was more luck than actual engineering practice, that it didn't break before.
> Fixed react runtime import by changing runtime react swc config

- packages/checkbox/types.ts
- packages/cookie-theme-toggler/cookie-theme-toggler.tsx
- packages/select/types.ts
Some props had excessively restrictive typings, so replaced string with ReactNode where possible
> Replaced string props with ReactNode

- packages/identicon/Identicon.tsx
Follow up for #460 
It turned out, that imports from `react-jazzicon` are breaking in runtime.
This PR fixes it.
> Fix broken esm imports from react-jazzicon

- package.json
Follow-up for https://github.com/lidofinance/ui/pull/460
`type: module` field makes stake widget on next.js to treat this module as ESM.
It fixes incompatibility with reef-knot on the widget, which was the reason of all this changes.
But it creates another unexpected problem on the widget during SSR of the pages with `styled-components` import, which looks like this:
```
error - TypeError: d is not a function
at <...>/ethereum-staking-widget/node_modules/styled-components/dist/styled-components.cjs.js:1:18879
at <...>
```
`d` here is a default export, which most likely is `undefined`.
Looks like node imports styled-components as cjs (because it is SSR) and something goes wrong.
The widget's bundle for browsers contains `__webpack_require__` calls for `styled-components.browser.esm.js` and …
> Remove `type: module` from package.json

- packages/input/Input.tsx
Passed `disabled` and `id` states to inner input, they were missed during previous refactoring of props passing logic :( 
https://github.com/lidofinance/ui/assets/103929444/6edd4e12-69e4-4e69-a7aa-fe29ff05892c
> Passed missed disabled & id props

- packages/theme/cookie-theme-provider.tsx
- packages/theme/document-head-contents/element-theme-script.tsx
This approach will be used in cases when ethereum widget is embeded to third-party app. It will give them ability to control color scheme according their ui appearance and their user settings.
> feat: parse theme from query param

- packages/styled-system/withStyledSystem.tsx
Added var wrapper 
```
const shouldForwardProp = _shouldForwardProp.default || _shouldForwardProp
```
for importing `'@styled-system/should-forward-prop'`
> fix: import default interop in styled-system

- packages/theme/cookie-theme-provider.tsx
Fix a hydration error in components using `withStyledSystem` wrapper when get a theme from query param. Actual on SSR mode only.
> fix: hydration when pass a theme as query param

- packages/modal/Modal.stories.tsx
- packages/modal/Modal.tsx
- packages/modal/ModalStyles.tsx
- packages/modal/types.tsx
* [`packages/modal/types.tsx`](diffhunk://#diff-efed8bc982b8db9f68e5ac548d08be5c8a3f203084504e3ea7b1e1072e2a8db7R27-R38): Added a `windowSize` prop to `ModalProps`, defined an enum `ModalWindowSize` with size options (`sm`, `md`, `lg`), and created a type alias `ModalWindowSizes` for the keys of the enum. Also introduced a `windowProps` prop for additional customization.
* [`packages/modal/Modal.tsx`](diffhunk://#diff-fd92dcaa18aca0a103d4e251fb91090229b0a22955ccc39e0c0e6ef6cfbc400bR29-R30): Updated the `Modal` component to accept the `windowSize` prop (defaulting to `'sm'`) and pass it, along with `windowProps`, to the styled component. [[1]](diffhunk://#diff-fd92dcaa18aca0a103d4e251fb91090229b0a22955ccc39e0c0e6ef6cfbc400bR29-R30) …
> feat: add window size support to Modal component and window props
